clear; close; clc;

%% system parameters values ===============================================
% the inertia matrix with respect to the body-fixed frame
J11 = 0.0820; J22 = 0.0845; J33 = 0.1377;
Jinertia = blkdiag(J11,J22,J33);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.315;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 8.004e-3;







%% run the system, omega only =============================================

% Define external torque (can be constant or time-dependent)
tau = [0.0; 0.0; 0.0]; % Constant torque in x-direction

% Initial angular velocity [rad/s]
omega0 = [0.01; 0.02; -0.01];

% Time span for simulation
tspan = [0 400];



% solve the ODE, solve Euler equations for ω(t)
options = odeset('RelTol',1e-5,'AbsTol',1e-8);
[t, omega] = ode45(@(t, y) euler_equation(t, y, Jinertia, tau), tspan, omega0, options);


% Plot results
figure;
plot(t, omega(:, 1), 'r', 'LineWidth', 2); hold on;
plot(t, omega(:, 2), 'g', 'LineWidth', 2);
plot(t, omega(:, 3), 'b', 'LineWidth', 2);
xlabel('Time (s)');
ylabel('Angular Velocity (rad/s)');
legend('\omega_1', '\omega_2', '\omega_3');
title('Evolution of Angular Velocity (Body Frame)');
grid on;









%% run the system, omega and rotation matrix ==============================
close;

% Inertia tensor
Jinertia = diag([1.0, 1.0, 1.0]);      

% Define external torque (can be constant or time-dependent)
tau = [0.0; 0.0; 0.0]; % Constant torque in x-direction

% Initial angular velocity [rad/s]
omega0 = [0.1; 0.1; 0.0];
% Initial rotation matrix
R0 = eye(3);   
% Combined state vector: [ω; R_flat] where R_flat is R(:)
y0 = [omega0; R0(:)];

% Time span for simulation
tspan = [0 400];



% Solve coupled system
options = odeset('RelTol', 1e-6, 'AbsTol', 1e-8);
[t, y] = ode45(@(t,y) ODE_omega_and_R(t,y,Jinertia,tau), tspan, y0, options);


% Extract results
omega = y(:,1:3)';
R = reshape(y(:,4:end)', 3, 3, []);

% check norm error
orth_error = zeros(size(R,3),1);
for k = 1:size(R,3)
    orth_error(k) = norm(R(:,:,k)*R(:,:,k)' - eye(3), 'fro');
end
% plot(t, orth_error);
% title('norm(R(t))-1');

% Visualization
visualize_rotation(t, R);






















%% useful functions =======================================================

% system dynamics, euler equation
function domega_dt = euler_equation(t, omega, I, torque)
    % Input:
    %   t: time (not used if torque is constant)
    %   omega: angular velocity vector [omega_1; omega_2; omega_3]
    %   I: inertia tensor (3x3 matrix)
    %   torque: external torque (can be a function or constant)
    
    % Compute the torque (if it's a function of time)
    if isa(torque, 'function_handle')
        tau = torque(t);
    else
        tau = torque; % constant torque
    end

    % Compute the cross product term omega x (I * omega)
    I_omega = I * omega;
    cross_term = cross(omega, I_omega);
    
    % Solve for domega/dt: I * domega/dt = tau - omega x (I * omega)
    domega_dt = I \ (tau - cross_term);
end




% Coupled ODE function, omega(t) and R(t)
function dy = ODE_omega_and_R(t, y, I, torque)

    % DE_omega_and_R Computes derivatives for coupled rigid body dynamics
    %
    % This function evaluates the time derivatives of both angular velocity (ω) 
    % and rotation matrix (R) for a rigid body with given inertia tensor,
    % combining Euler's equations and rotation matrix kinematics.
    %
    % Inputs:
    %   t     : Current time (scalar)
    %   y     : Combined state vector [ω; R_flat] where:
    %           - ω (3x1 vector) is angular velocity in body frame [rad/s]
    %           - R_flat (9x1 vector) is flattened rotation matrix (R(:))
    %   I     : Inertia tensor (3x3 matrix) in body frame [kg·m²]
    %   torque : External torque vector (3x1) in body frame [N·m]
    %            (Can be function handle torque(t) or constant vector)
    %
    % Output:
    %   dy    : Time derivative of state vector [dω/dt; dR_flat/dt]
    %
    % Equations:
    %   I*dω/dt = torque - ω×(Iω)  (Euler's equation)
    %   dR/dt = R*[ω]×             (Rotation matrix kinematics)
    %   where [ω]× is the skew-symmetric cross product matrix

    % Compute the torque (if it's a function of time)
    if isa(torque, 'function_handle')
        tau = torque(t);
    else
        tau = torque; % constant torque
    end

    % Extract ω and R from state vector
    omega = y(1:3);
    R = reshape(y(4:end), 3, 3);
    
    % Euler equation for dω/dt
    cross_term = cross(omega, I*omega);
    domega_dt = I \ (tau - cross_term);
    
    % Rotation matrix equation dR/dt = R*[ω]×
    omega_skew = [0, -omega(3), omega(2);
                 omega(3), 0, -omega(1);
                 -omega(2), omega(1), 0];
    dRdt = R * omega_skew;
    
    % Combine derivatives
    dy = [domega_dt; dRdt(:)];
end




function visualize_rotation(t, R)
    % Define cube vertices (1x1x1 cube centered at origin)
    vertices = [-0.5 -0.5 -0.5;   % Vertex 1
                0.5 -0.5 -0.5;    % Vertex 2
                0.5  0.5 -0.5;    % Vertex 3
               -0.5  0.5 -0.5;    % Vertex 4
               -0.5 -0.5  0.5;    % Vertex 5
                0.5 -0.5  0.5;    % Vertex 6
                0.5  0.5  0.5;    % Vertex 7
               -0.5  0.5  0.5];   % Vertex 8

    % Define cube edges (vertex connections)
    edges = [1 2; 2 3; 3 4; 4 1;  % Bottom face
             5 6; 6 7; 7 8; 8 5;  % Top face
             1 5; 2 6; 3 7; 4 8]; % Vertical edges

    % Initialize figure
    figure;
    axis equal;
    axis([-1 1 -1 1 -1 1]*1.5);
    xlabel('X'); ylabel('Y'); zlabel('Z');
    title('Rigid Body Rotation Visualization');
    grid on;
    view(3);
    set(gca, 'Projection', 'perspective');
    
    % Set lighting for better 3D perception
    lighting gouraud;
    light('Position',[1 1 1],'Style','infinite');
    material shiny;

    % Draw inertial frame axes
    hold on;
    quiver3(0,0,0,1,0,0,'r','LineWidth',2,'MaxHeadSize',0.5); % X-axis
    quiver3(0,0,0,0,1,0,'g','LineWidth',2,'MaxHeadSize',0.5); % Y-axis
    quiver3(0,0,0,0,0,1,'b','LineWidth',2,'MaxHeadSize',0.5); % Z-axis
    text(1.1,0,0,'X','Color','r','FontSize',12);
    text(0,1.1,0,'Y','Color','g','FontSize',12);
    text(0,0,1.1,'Z','Color','b','FontSize',12);

    % Pre-allocate edge graphics objects
    edge_handles = gobjects(size(edges,1),1);
    for k = 1:size(edges,1)
        edge_handles(k) = plot3([0 0], [0 0], [0 0], ...
                              'Color', [0.2 0.6 1], 'LineWidth', 2);
    end

    % Animation loop
    for i = 1:1:length(t)
        % Transform vertices using current rotation matrix
        rotated_vertices = (R(:,:,i) * vertices')';
        
        % Update all edges
        for k = 1:size(edges,1)
            v1 = rotated_vertices(edges(k,1),:);
            v2 = rotated_vertices(edges(k,2),:);
            set(edge_handles(k), ...
                'XData', [v1(1) v2(1)], ...
                'YData', [v1(2) v2(2)], ...
                'ZData', [v1(3) v2(3)]);
        end
        
        % Draw body-fixed frame
        R_current = R(:,:,i);
        delete(findobj(gca,'Type','quiver','UserData','body_frame'));
        quiver3(0,0,0,R_current(1,1),R_current(2,1),R_current(3,1),'r',...
               'LineWidth',1,'UserData','body_frame','MaxHeadSize',0.3);
        quiver3(0,0,0,R_current(1,2),R_current(2,2),R_current(3,2),'g',...
               'LineWidth',1,'UserData','body_frame','MaxHeadSize',0.3);
        quiver3(0,0,0,R_current(1,3),R_current(2,3),R_current(3,3),'b',...
               'LineWidth',1,'UserData','body_frame','MaxHeadSize',0.3);
        
        % Display current time
        if ~isempty(findobj(gca,'Type','text','String','Time:'))
            delete(findobj(gca,'Type','text','String','Time:'));
        end
        % text(1,1,1.4,sprintf('Time: %.2f s',t(i)),'FontSize',5);
        
        drawnow limitrate; % Optimized rendering
    end
end





























