
clear; close; clc;

%% system settings ========================================================
% Time step [s]
h = 0.01;  

% mass
mass = 1.440;
% the inertia matrix with respect to the body-fixed frame
Jx = 0.01667744559662811; 
Jy = 0.017723765387827547; 
Jz = 0.029656688514293567;
Jinertia = blkdiag(Jx,Jy,Jz);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.13;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 0.08;

% system dimension
dim_x = 6;
dim_u = 3;
     




%% generate experimental data =============================================



% Simulation parameters
tspan = [0 0.3]; % Time range [s]
num_steps = length(tspan(1):h:tspan(2));


% torque maganitude
eu = 1.0;

% multiple trajectory
num_traj = 30;

Dstate0 = zeros(dim_x, num_steps-1, num_traj); Dstate1 = Dstate0; 
Dinput0 = zeros(dim_u, num_steps-1, num_traj);


for itr = 1:num_traj
    % Initial state: [roll; pitch; yaw; omega_x; omega_y; omega_z]
    state0 = randn(dim_x,1)*0.1; 
    tau_exp = 2*eu*rand(dim_u,num_steps-1) - eu; % uniformly distributed within the interval [-eu eu] 
    
    % Torque function that steps through pre-generated values
    tau_f = @(t,state) tau_exp(:, round(t/h)+1);
    
    % Run the system
    [t_exp, x_exp] = discrete_attitude_equation(Jinertia, state0, tau_f, h, tspan);
    x_exp = x_exp';
    
    % store the data
    Dstate0(:,:,itr) = x_exp(:,1:num_steps-1);
    Dstate1(:,:,itr) = x_exp(:,2:num_steps);
    Dinput0(:,:,itr) = tau_exp;
end



% Plot first 3 curves in Figure 1
figure(1); hold on;            
for i = 1:3        
    plot(t_exp', x_exp(i, :), 'LineWidth', 1.5);
end
hold off;           % Release figure hold
legend('Curve 1', 'Curve 2', 'Curve 3');
grid on;

% Plot last 3 curves in Figure 2
figure(2); hold on;            
for i = 4:6         
    plot(t_exp', x_exp(i, :), 'LineWidth', 1.5);
end
hold off;           % Release figure hold
legend('Curve 4', 'Curve 5', 'Curve 6');
grid on;






%% useful functions =======================================================

function [t_discrete, state_discrete] = discrete_attitude_equation(I, state0, tau_fun, h, tspan)
    % Discrete-time Attitude Dynamics Solver (Forward Euler Method)
    % Solves coupled Euler-angle kinematics and Euler's rotation equations.
    %
    % Inputs:
    %   I: 3x3 inertia matrix [kg*m^2] (diagonal or full)
    %   state0: Initial state [phi; theta; psi; omega_x; omega_y; omega_z] (6x1)
    %           Angles in radians, angular rates in rad/s
    %   tau_fun: Torque function handle(t,state) OR constant torque vector (3x1) [N*m]
    %   h: Time step size [s] (scalar)
    %   tspan: Time range [t_start, t_end] [s]
    % 
    % Outputs:
    %   t_discrete: Time vector (Nx1) [s]
    %   state_discrete: State history [phi,theta,psi,omega_x,omega_y,omega_z] (Nx6)
    %                   Angles in radians, angular rates in rad/s

    % Initialize time vector (column)
    t_discrete = (tspan(1):h:tspan(2))';
    N = length(t_discrete);
    state_discrete = zeros(N, 6);
    state_discrete(1,:) = state0(:)';  % Ensure row vector storage

    % Time-stepping loop
    for k = 1:N-1
        t_k = t_discrete(k);
        state_k = state_discrete(k,:)';  % Convert to column vector
        
        % Split state into Euler angles and angular velocity
        angles_k = state_k(1:3);  % [phi; theta; psi] in rad
        omega_k = state_k(4:6);   % [omega_x; omega_y; omega_z] in rad/s
        
        % Evaluate torque (handle both function and constant torque)
        if isa(tau_fun, 'function_handle')
            tau_k = tau_fun(t_k, state_k);  % Time/state-dependent torque
        else
            tau_k = tau_fun;               % Constant torque
        end
        
        % --- Kinematic Equations (ZYX Euler Angles) ---
        phi = angles_k(1);    % Roll [rad]
        theta = angles_k(2);  % Pitch [rad]
        
        % Singularity check (gimbal lock)
        if abs(cos(theta)) < 1e-1
            error('Gimbal lock: Pitch=±90°. Switch to quaternions.');
        end
        
        % Euler angle derivatives (ZYX order)
        phi_dot = omega_k(1) + sin(phi)*tan(theta)*omega_k(2) + cos(phi)*tan(theta)*omega_k(3);
        theta_dot = cos(phi)*omega_k(2) - sin(phi)*omega_k(3);
        psi_dot = (sin(phi)/cos(theta))*omega_k(2) + (cos(phi)/cos(theta))*omega_k(3);
        euler_dot = [phi_dot; theta_dot; psi_dot];
        
        % --- Dynamic Equations (Euler's Rotation Equations) ---
        % Note: I must be invertible (positive definite)
        omega_dot = I \ (tau_k - cross(omega_k, I*omega_k));
        
        % Forward Euler integration
        state_discrete(k+1,:) = (state_k + h * [euler_dot; omega_dot])';
    end
end






