
clear; close; clc;

%% system settings ========================================================
% Time step [s]
h = 0.01;  

% mass
mass = 1.440;
% the inertia matrix with respect to the body-fixed frame
Jx = 0.01667744559662811; 
Jy = 0.017723765387827547; 
Jz = 0.029656688514293567;
Jinertia = blkdiag(Jx,Jy,Jz);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.13;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 0.08;

% system dimension
dim_x = 6;
dim_u = 3;
     


% xiA1 = [ 1 ];
f_xiA1 = @(x) 1;
EA1 = [1; 0; 0; 0; 0; 0];
dim_xiA1 = 1;
% xiA2 = [ 1 ];
f_xiA2 = @(x) 1;
EA2 = [0; 1; 0; 0; 0; 0];
dim_xiA2 = 1;
% xiA3 = [ 1 ];
f_xiA3 = @(x) 1;
EA3 = [0; 0; 1; 0; 0; 0];
dim_xiA3 = 1;
% xiA4 = [ 1; x6 ];
f_xiA4 = @(x) [1; x(6)];
EA4 = [ h,            0; 
        0,            0; 
        0,            0; 
        1,            0; 
        0, h*(Jz-Jx)/Jy; 
        0,            0 ];
dim_xiA4 = 2;
% xiA5 = [ 1; sin(x1)*tan(x2); cos(x1); sin(x1)/cos(x2); x4 ];
f_xiA5 = @(x) [1; sin(x(1))*tan(x(2)); cos(x(1)); sin(x(1))/cos(x(2)); x(4)];
EA5 = [ 0, h, 0, 0, 0; 
        0, 0, h, 0, 0;
        0, 0, 0, h, 0;
        0, 0, 0, 0, 0;
        1, 0, 0, 0, 0;
        0, 0, 0, 0, h*(Jx-Jy)/Jz ];
dim_xiA5 = 5;
% xiA6 = [ 1; cos(x1)*tan(x2); sin(x1); cos(x1)/cos(x2); x5 ];
f_xiA6 = @(x) [ 1; cos(x(1))*tan(x(2)); sin(x(1)); cos(x(1))/cos(x(2)); x(5) ];
EA6 = [ 0, h,  0, 0, 0; 
        0, 0, -h, 0, 0;
        0, 0,  0, h, 0;
        0, 0,  0, 0, h*(Jy-Jz)/Jx;
        0, 0,  0, 0, 0;
        1, 0,  0, 0, 0 ];
dim_xiA6 = 5;
dim_xiA = dim_xiA1+dim_xiA2+dim_xiA3+dim_xiA4+dim_xiA5+dim_xiA6;
% xiB1 = [ 1 ];
f_xiB1 = @(x) 1;
EB1 = [0, 0, 0, h/Jx, 0, 0]';
dim_xiB1 = 1;
% xiB2 = [ 1 ];
f_xiB2 = @(x) 1;
EB2 = [0, 0, 0, 0, h/Jy, 0]';
dim_xiB2 = 1;
% xiB3 = [ 1 ];
f_xiB3 = @(x) 1;
EB3 = [0, 0, 0, 0, 0, h/Jz]';
dim_xiB3 = 1;
dim_xiB = dim_xiB1+dim_xiB2+dim_xiB3;






%% generate experimental data =============================================



% Simulation parameters
tspan = [0 0.3]; % Time range [s]
num_steps = length(tspan(1):h:tspan(2));


% torque maganitude
eu = 1.2;

% multiple trajectory
num_traj = 30;

Dstate0 = zeros(dim_x, num_steps-1, num_traj); Dstate1 = Dstate0; 
Dinput0 = zeros(dim_u, num_steps-1, num_traj);

bXI0 = zeros(dim_xiA, num_steps-1); 
bXI1 = zeros(dim_x, num_steps-1);
bUI0 = zeros(dim_xiB, num_steps-1);

BXI1 = []; BXI0 = []; BUI0 = [];

for itr = 1:num_traj
    % Initial state: [roll; pitch; yaw; omega_x; omega_y; omega_z]
    state0 = randn(dim_x,1)*0.1; 
    tau_exp = 2*eu*rand(dim_u,num_steps-1) - eu;
    % Torque function that steps through pre-generated values
    tau_f = @(t,state) tau_exp(:, round(t/h)+1);
    % Run the system
    [t_exp, x_exp] = discrete_attitude_equation(Jinertia, state0, tau_f, h, tspan);
    x_exp = x_exp';
    Dstate0(:,:,itr) = x_exp(:,1:num_steps-1);
    Dstate1(:,:,itr) = x_exp(:,2:num_steps);
    Dinput0(:,:,itr) = tau_exp;

    for ik = 1:num_steps-1
        bXI0(:,ik) = blkdiag( f_xiA1(x_exp(:,ik)), ...
                              f_xiA2(x_exp(:,ik)), ...
                              f_xiA3(x_exp(:,ik)), ...
                              f_xiA4(x_exp(:,ik)), ...
                              f_xiA5(x_exp(:,ik)), ...
                              f_xiA6(x_exp(:,ik)) ...
                             ) * x_exp(:,ik); 
        
        bUI0(:,ik) = blkdiag( f_xiB1(x_exp(:,ik)), ...
                              f_xiB2(x_exp(:,ik)), ...
                              f_xiB3(x_exp(:,ik)) ...
                             ) * tau_exp(:,ik); 
    end
    bXI1 = x_exp(:,2:num_steps);
    BXI1 = [BXI1, bXI1];
    BXI0 = [BXI0, bXI0];
    BUI0 = [BUI0, bUI0];
end



% Plot first 3 curves in Figure 1
figure(1); hold on;            
for i = 1:3        
    plot(t_exp', x_exp(i, :), 'LineWidth', 0.5);
end
hold off;           % Release figure hold
legend('Curve 1', 'Curve 2', 'Curve 3');
grid on;

% Plot last 3 curves in Figure 2
figure(2); hold on;            
for i = 4:6         
    plot(t_exp', x_exp(i, :), 'LineWidth', 0.5);
end
hold off;           % Release figure hold
legend('Curve 4', 'Curve 5', 'Curve 6');
grid on;




DATATEST = [EA1, EA2, EA3, EA4, EA5, EA6]*BXI0 + [EB1, EB2, EB3]*BUI0 - BXI1;
figure('Color','w');
plot(DATATEST(4,:));

dataA = [BXI0; BUI0]*[BXI0; BUI0]';
dataB = -BXI1*[BXI0; BUI0]';
dataC = BXI1*BXI1';

disp("min eig is " + min(eig(dataA)));









%% solve the controller ===================================================

% set the domain: |x| <= rx
rx = 0.5; 

% XIA
xiA11 = 1;

xiA12 = 1;

xiA13 = 1;

xiA14 = 1;
xiA24_u = rx; xiA24_l = -rx; 

xiA15 = 1;
xiA25_u = sin(rx)*tan(rx) ; xiA25_l = -sin(rx)*tan(rx);
xiA35_u = 1; xiA35_l = cos(rx);
xiA45_u = sin(rx)/cos(rx); xiA45_l = -sin(rx)/cos(rx);
xiA55_u = rx; xiA55_l = -rx;

xiA16 = 1;
xiA26_u = tan(rx) ; xiA26_l = -tan(rx);
xiA36_u = sin(rx) ; xiA36_l = -sin(rx);
xiA46_u = 1/cos(rx) ; xiA46_l = cos(rx);
xiA56_u = rx; xiA56_l = -rx;

% XIB
xiB11 = 1;
xiB12 = 1;
xiB13 = 1;

% the set of barQ
barQ = funcBarQ(xiA11, xiA12, xiA13, ...
                xiA14, xiA24_u, xiA24_l, ...
                xiA15, xiA25_u, xiA25_l, xiA35_u, xiA35_l, xiA45_u, xiA45_l, xiA55_u, xiA55_l, ...
                xiA16, xiA26_u, xiA26_l, xiA36_u, xiA36_l, xiA46_u, xiA46_l, xiA56_u, xiA56_l, ...
                xiB11, xiB12, xiB13);


% solve sdp LMI
cvx_solver mosek  % sdpt3
cvx_begin sdp % quiet
    variable epGa semidefinite;
    variable lyGa(dim_x,dim_x) semidefinite;
    variable kY(dim_u,dim_x);
    % variable mu_l semidefinite;
    % variable mu_u semidefinite;
    
    % minimize( mu_u - 0*mu_l + 1*epGa );
    minimize( 0.4*lambda_max(lyGa) - lambda_min(lyGa) - 0.1*epGa - 0*trace(lyGa) );

    subject to   
        for iv = 1:length(barQ)
            blockS = [ -lyGa-dataC,   zeros(dim_x),          dataB;
                       zeros(dim_x), -lyGa+epGa*eye(dim_x), -[lyGa;kY]'*barQ{iv}'; 
                       dataB',       -barQ{iv}*[lyGa;kY],   -dataA ];
            blockS <= 0;
        end
        epGa >= 0.00001;
        lyGa >= 0.0001 * eye(dim_x);
        % lyGa >= mu_l * eye(dim_x);
        % lyGa <= (mu_l+mu_u) * eye(dim_x);
        
cvx_end

vK = kY/lyGa;

% region of attraction
roac = sqrt( maxEig(lyGa)*minEig(lyGa) / ( maxEig(lyGa)^2 - epGa*minEig(lyGa) ) );
roa  = min( 1, roac ) * rx;
disp("radius of ROA is " + roa);






%% controller implementation ==============================================

% state0_imp = ones(dim_x,1)*1;
state0_imp = [0.1 0.1 0.1 -0.1 -0.1 -0.1]';
tspan_imp = [0 10];

% Torque function that, state feedback
tau_fk = @(t,state) vK*state;
[t_imp, x_imp] = discrete_attitude_equation(Jinertia, state0_imp, tau_fk, h, tspan_imp);
x_imp = x_imp';


figure('color', [1 1 1]);
set(gcf, 'Position', [100, 100, 450, 350]);

subplot(2,1,1); % 2 rows, 1 column, 1st subplot
hold on;
for i = 1:3
    plot(t_imp', x_imp(i,:), 'LineWidth', 1.5);
end
hold off;
legend('$\phi$', '$\theta$', '$\psi$', 'Fontname', 'Times New Roman', 'Interpreter', 'latex', 'FontSize', 12);
xlabel('time [s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
ylabel('Euler angles [rad]', 'Fontname', 'Times New Roman', 'FontSize', 11);
set(gca,'fontsize',11,'fontname','Times');
grid on;
set(gca,'position',[0.13 0.63 0.84 0.32]);

% Bottom subplot - last 3 curves
subplot(2,1,2); % 2 rows, 1 column, 2nd subplot
hold on;
for i = 4:6
    plot(t_imp', x_imp(i,:), 'LineWidth', 1.5);
end
hold off;
legend('$\omega_1$', '$\omega_2$', '$\omega_3$', 'Fontname', 'Times New Roman', 'Interpreter', 'latex', 'FontSize', 12);
xlabel('time [s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
ylabel('angular velocity [rad/s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
set(gca,'fontsize',11,'fontname','Times');
grid on;
set(gca,'position',[0.13 0.15 0.84 0.32]);






%% useful functions =======================================================

function [t_discrete, state_discrete] = discrete_attitude_equation(I, state0, tau_fun, h, tspan)
    % Discrete-time Attitude Dynamics Solver (Forward Euler Method)
    % Solves coupled Euler-angle kinematics and Euler's rotation equations.
    %
    % Inputs:
    %   I: 3x3 inertia matrix [kg*m^2] (diagonal or full)
    %   state0: Initial state [phi; theta; psi; omega_x; omega_y; omega_z] (6x1)
    %           Angles in radians, angular rates in rad/s
    %   tau_fun: Torque function handle(t,state) OR constant torque vector (3x1) [N*m]
    %   h: Time step size [s] (scalar)
    %   tspan: Time range [t_start, t_end] [s]
    % 
    % Outputs:
    %   t_discrete: Time vector (Nx1) [s]
    %   state_discrete: State history [phi,theta,psi,omega_x,omega_y,omega_z] (Nx6)
    %                   Angles in radians, angular rates in rad/s

    % Initialize time vector (column)
    t_discrete = (tspan(1):h:tspan(2))';
    N = length(t_discrete);
    state_discrete = zeros(N, 6);
    state_discrete(1,:) = state0(:)';  % Ensure row vector storage

    % Time-stepping loop
    for k = 1:N-1
        t_k = t_discrete(k);
        state_k = state_discrete(k,:)';  % Convert to column vector
        
        % Split state into Euler angles and angular velocity
        angles_k = state_k(1:3);  % [phi; theta; psi] in rad
        omega_k = state_k(4:6);   % [omega_x; omega_y; omega_z] in rad/s
        
        % Evaluate torque (handle both function and constant torque)
        if isa(tau_fun, 'function_handle')
            tau_k = tau_fun(t_k, state_k);  % Time/state-dependent torque
        else
            tau_k = tau_fun;               % Constant torque
        end
        
        % --- Kinematic Equations (ZYX Euler Angles) ---
        phi = angles_k(1);    % Roll [rad]
        theta = angles_k(2);  % Pitch [rad]
        
        % Singularity check (gimbal lock)
        if abs(cos(theta)) < 1e-2
            error('Gimbal lock: Pitch=±90°. Switch to quaternions.');
        end
        
        % Euler angle derivatives (ZYX order)
        phi_dot = omega_k(1) + sin(phi)*tan(theta)*omega_k(2) + cos(phi)*tan(theta)*omega_k(3);
        theta_dot = cos(phi)*omega_k(2) - sin(phi)*omega_k(3);
        psi_dot = (sin(phi)/cos(theta))*omega_k(2) + (cos(phi)/cos(theta))*omega_k(3);
        euler_dot = [phi_dot; theta_dot; psi_dot];
        
        % --- Dynamic Equations (Euler's Rotation Equations) ---
        % Note: I must be invertible (positive definite)
        omega_dot = I \ (tau_k - cross(omega_k, I*omega_k));
        
        % Forward Euler integration
        state_discrete(k+1,:) = (state_k + h * [euler_dot; omega_dot])';
    end
end



function BarQ = funcBarQ(a1, a2, a3, ...
                         a14, a24_u, a24_l, ...
                         a15, a25_u, a25_l, a35_u, a35_l, a45_u, a45_l, a55_u, a55_l, ...
                         a16, a26_u, a26_l, a36_u, a36_l, a46_u, a46_l, a56_u, a56_l, ...
                         b1, b2, b3)
    % Generate all 512 (2^9) combinations of upper/lower variants
    % Inputs: 
    %   a* : Component matrices
    %   *_u : Upper bound variants
    %   *_l : Lower bound variants
    % Output:
    %   BarQ : 512x1 cell array of blkdiag matrices
    
    % Define all possible combinations (binary combinations for 9 parameters)
    combinations = dec2bin(0:511) - '0'; % 512x9 binary matrix
    
    % Preallocate output
    BarQ = cell(512, 1);
    
    % Generate each combination
    for i = 1:512
        % Select variants based on binary flags
        idx = combinations(i,:);
        
        % Choose a24 variant
        a24 = idx(1)*a24_u + (1-idx(1))*a24_l;
        
        % Choose a25/a35/a45/a55 variants
        a25 = idx(2)*a25_u + (1-idx(2))*a25_l;
        a35 = idx(3)*a35_u + (1-idx(3))*a35_l;
        a45 = idx(4)*a45_u + (1-idx(4))*a45_l;
        a55 = idx(5)*a55_u + (1-idx(5))*a55_l;
        
        % Choose a26/a36/a46/a56 variants
        a26 = idx(6)*a26_u + (1-idx(6))*a26_l;
        a36 = idx(7)*a36_u + (1-idx(7))*a36_l;
        a46 = idx(8)*a46_u + (1-idx(8))*a46_l;
        a56 = idx(9)*a56_u + (1-idx(9))*a56_l;
        
        % Build the block diagonal matrix
        BarQ{i} = blkdiag(a1, a2, a3, ...
                          [a14; a24], ...
                          [a15; a25; a35; a45; a55], ...
                          [a16; a26; a36; a46; a56], ...
                          b1, b2, b3);
    end
end


function e_max = maxEig( MatrixSym )
    e_max = max(eig(MatrixSym));
end

function e_min = minEig( MatrixSym )
    e_min = min(eig(MatrixSym));
end





