clear; close; clc;

%% system parameters values ===============================================
% the inertia matrix with respect to the body-fixed frame
J11 = 0.0820; J22 = 0.0845; J33 = 0.1377;
Jinertia = blkdiag(J11,J22,J33);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.315;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 8.004e-3;







%% run the system, omega only =============================================

% Define external torque (can be constant or time-dependent)
tau = [0.0; 0.0; 0.0]; % Constant torque in x-direction

% Initial angular velocity [rad/s]
omega0 = [0.01; -0.01; 0.01];

% Time span for simulation
tspan = [0 4000];

% Time step for discrete method
h = 0.01;                           



% solve the ODE, solve Euler equations for ω(t)
options = odeset('RelTol',1e-6,'AbsTol',1e-9);
[t_ode, omega_ode] = ode45(@(t, y) euler_equation(t, y, Jinertia, tau), tspan, omega0, options);


% run discretize the system
[t_discrete, omega_discrete] = discrete_euler_equation(Jinertia, omega0, tau, h, tspan);




% Plot comparison
[t_sampled, omega_sampled] = sample_discrete_solution(t_discrete, omega_discrete, length(t_ode));

% Plot comparison
figure;
component_names = {'\omega_1', '\omega_2', '\omega_3'};
for i = 1:3
    subplot(3,1,i);
    plot(t_ode, omega_ode(:,i), 'b-', 'LineWidth', 1.5); hold on;
    plot(t_sampled, omega_sampled(:,i), 'ro--', 'LineWidth', 1);
    ylabel(component_names{i});
    legend('ode45', 'Discrete Euler (sampled)');
    grid on;
end
xlabel('Time (s)');
% sgtitle('Comparison of Rigid Body Euler Equations: ODE45 vs. Discrete Euler');








%% phase portrait =========================================================

% Define moment of inertia and control parameters
k = 1;                      % Control gain
K = -k * eye(3);              % Feedback matrix
B = inv(Jinertia);            % Input matrix
% Precompute B*K for efficiency
BK = B*K;

% === Grid ===
n = 10;
range = 50;
[x1, x2, x3] = meshgrid(linspace(-range, range, n));

% === Evaluate vector field ===
[dx1, dx2, dx3] = compute_closed_loop_field(x1, x2, x3, Jinertia, BK);

% === Plot ===
figure('Color','w');
quiver3(x1, x2, x3, dx1, dx2, dx3, 'AutoScaleFactor', 0.8, 'MaxHeadSize', 0.3);
xlabel('\omega_1'); ylabel('\omega_2'); zlabel('\omega_3');
title('Closed-loop Phase Portrait of Rigid Body');
axis tight; grid on; view(3);

% Optional streamlines
hold on;
startx = -range * ones(1, 10);
starty = linspace(-range, range, 10);
startz = zeros(1, 10);
streamline(x1, x2, x3, dx1, dx2, dx3, startx, starty, startz);











%% useful functions =======================================================

% system dynamics, euler equation
function domega_dt = euler_equation(t, omega, I, torque)
    % Input:
    %   t: time (not used if torque is constant)
    %   omega: angular velocity vector [omega_1; omega_2; omega_3]
    %   I: inertia tensor (3x3 matrix)
    %   torque: external torque (can be a function or constant)
    
    % Compute the torque (if it's a function of time)
    if isa(torque, 'function_handle')
        tau = torque(t);
    else
        tau = torque; % constant torque
    end

    % Compute the cross product term omega x (I * omega)
    I_omega = I * omega;
    cross_term = cross(omega, I_omega);
    
    % Solve for domega/dt: I * domega/dt = tau - omega x (I * omega)
    domega_dt = I \ (tau - cross_term);
end



% Discrete-time Euler equations
% ω(k+1) = ω(k) + h J^−1 ( −ω(k) × Jω(k) ) + h J^−1 τ(k)
function [t_discrete, omega_discrete] = discrete_euler_equation(I, omega0, tau_fun, h, tspan)
    % Discrete-time Euler equations for rigid body rotation (Forward Euler method)
    %
    % Inputs:
    %   I        : Inertia tensor (3x3 matrix)
    %   omega0   : Initial angular velocity vector (3x1)
    %   tau_fun  : External torque (either a constant 3x1 vector or function handle @(t, omega))
    %   h        : Time step size
    %   tspan    : Time interval as [t0, tf]
    %
    % Outputs:
    %   t_discrete      : Discrete time vector (N x 1)
    %   omega_discrete  : Angular velocity (N x 3)

    % Initialize time vector as column
    t_discrete = (tspan(1):h:tspan(2))';
    N = length(t_discrete);
    omega_discrete = zeros(N, 3);
    omega_discrete(1,:) = omega0(:)';

    % Time-stepping loop
    for k = 1:N-1
        t_k = t_discrete(k);
        omega_k = omega_discrete(k,:)';

        % Evaluate torque
        if isa(tau_fun, 'function_handle')
            tau_k = tau_fun(t_k, omega_k);
        else
            tau_k = tau_fun;
        end

        % Compute angular acceleration
        omega_dot = I \ (tau_k - cross(omega_k, I * omega_k));

        % Forward Euler update
        omega_discrete(k+1,:) = (omega_k + h * omega_dot)';
    end
end



function [t_sampled, omega_sampled] = sample_discrete_solution(t_discrete, omega_discrete, N_target)
    % Uniformly downsample the discrete solution to match the number of points in ODE solution
    %
    % Inputs:
    %   t_discrete      : Full discrete time vector (N x 1)
    %   omega_discrete  : Full discrete omega matrix (N x 3)
    %   N_target        : Number of points to sample (e.g., length(t_ode))
    %
    % Outputs:
    %   t_sampled       : Sampled time vector (N_target x 1)
    %   omega_sampled   : Sampled omega matrix (N_target x 3)

    N_full = length(t_discrete);

    % Generate equally spaced indices
    idx = round(linspace(1, N_full, N_target));
    idx = min(idx, N_full); % Prevent indexing overflow

    % Sample
    t_sampled = t_discrete(idx);
    omega_sampled = omega_discrete(idx, :);
end



function [dx1, dx2, dx3] = compute_closed_loop_field(x1, x2, x3, J, BK)
    J1 = J(1,1); J2 = J(2,2); J3 = J(3,3);

    dx1 = (J2 - J3)/J1 * x2 .* x3 + BK(1,1)*x1 + BK(1,2)*x2 + BK(1,3)*x3;
    dx2 = (J3 - J1)/J2 * x3 .* x1 + BK(2,1)*x1 + BK(2,2)*x2 + BK(2,3)*x3;
    dx3 = (J1 - J2)/J3 * x1 .* x2 + BK(3,1)*x1 + BK(3,2)*x2 + BK(3,3)*x3;
end

























