clear; close all; clc;

%% system settings ========================================================
% Time step [s]
h = 0.01; 

% the inertia matrix with respect to the body-fixed frame
Jx = 0.0820; Jy = 0.0845; Jz = 0.1377;
Jinertia = blkdiag(Jx,Jy,Jz);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.315;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 8.004e-3;
% force to torque matrix
Bf2tau = [ 0,       d_c2c,    0,      -d_c2c;
           d_c2c,   0,       -d_c2c,   0;
          -c_f2tau, c_f2tau, -c_f2tau, c_f2tau ];
BinM = [zeros(3,3); eye(3)/Jinertia]*Bf2tau*h;



% system dimension
dim_x = 6;
dim_u = 4;
      


% xiA1 = [ 1 ];
f_xiA1 = @(x) 1;
EA1 = [1; 0; 0; 0; 0; 0];
dim_xiA1 = 1;
% xiA2 = [ 1 ];
f_xiA2 = @(x) 1;
EA2 = [0; 1; 0; 0; 0; 0];
dim_xiA2 = 1;
% xiA3 = [ 1 ];
f_xiA3 = @(x) 1;
EA3 = [0; 0; 1; 0; 0; 0];
dim_xiA3 = 1;
% xiA4 = [ 1; x6 ];
f_xiA4 = @(x) [1; x(6)];
EA4 = [ h,            0; 
        0,            0; 
        0,            0; 
        1,            0; 
        0, h*(Jz-Jx)/Jy; 
        0,            0 ];
dim_xiA4 = 2;
% xiA5 = [ 1; sin(x1)*tan(x2); cos(x1); sin(x1)/cos(x2); x4 ];
f_xiA5 = @(x) [1; sin(x(1))*tan(x(2)); cos(x(1)); sin(x(1))/cos(x(2)); x(4)];
EA5 = [ 0, h, 0, 0, 0; 
        0, 0, h, 0, 0;
        0, 0, 0, h, 0;
        0, 0, 0, 0, 0;
        1, 0, 0, 0, 0;
        0, 0, 0, 0, h*(Jx-Jy)/Jz ];
dim_xiA5 = 5;
% xiA6 = [ 1; cos(x1)*tan(x2); sin(x1); cos(x1)/cos(x2); x5 ];
f_xiA6 = @(x) [ 1; cos(x(1))*tan(x(2)); sin(x(1)); cos(x(1))/cos(x(2)); x(5) ];
EA6 = [ 0, h,  0, 0, 0; 
        0, 0, -h, 0, 0;
        0, 0,  0, h, 0;
        0, 0,  0, 0, h*(Jy-Jz)/Jx;
        0, 0,  0, 0, 0;
        1, 0,  0, 0, 0 ];
dim_xiA6 = 5;
dim_xiA = dim_xiA1+dim_xiA2+dim_xiA3+dim_xiA4+dim_xiA5+dim_xiA6;

% xiB1 = [ 1 ];
f_xiB1 = @(x) 1;
EB1 = BinM(:,1);
dim_xiB1 = 1;
% xiB2 = [ 1 ];
f_xiB2 = @(x) 1;
EB2 = BinM(:,2);
dim_xiB2 = 1;
% xiB3 = [ 1 ];
f_xiB3 = @(x) 1;
EB3 = BinM(:,3);
dim_xiB3 = 1;
% xiB4 = [ 1 ];
f_xiB4 = @(x) 1;
EB4 = BinM(:,4);
dim_xiB4 = 1;
dim_xiB = dim_xiB1+dim_xiB2+dim_xiB3+dim_xiB4;






%% generate experimental data =============================================



% Simulation parameters
tspan = [0, 0.35]; % Time range [s]
num_steps = length(tspan(1):h:tspan(2));


% force maganitude
eu = 20;

% disturbance maganitude
ed = 0.0002;

% multiple trajectory
num_traj = 40;

Dstate0 = zeros(dim_x, num_steps-1, num_traj); Dstate1 = Dstate0; 
Dinput0 = zeros(dim_u, num_steps-1, num_traj); Ddistu0 = Dstate1;

bXI0 = zeros(dim_xiA, num_steps-1); 
bXI1 = zeros(dim_x, num_steps-1); bDI0 = bXI1;
bUI0 = zeros(dim_xiB, num_steps-1);

BXI1 = []; BXI0 = []; BUI0 = []; BDI0 = [];

for itr = 1:num_traj
    % Initial state: [roll; pitch; yaw; omega_x; omega_y; omega_z]
    state0 = randn(dim_x,1)*0.1; 

    % input sequence
    % force_exp = 2*eu*rand(dim_u,num_steps-1) - eu;
    force_exp = eu*rand(dim_u,num_steps-1);
    % force function that steps through pre-generated values
    force_f = @(t,state) force_exp(:, round(t/h)+1);

    % disturbance sequence
    dis_exp = 2*ed*rand(dim_x,num_steps-1) - ed;
    % disturbance function that steps through pre-generated values
    dis_f = @(t,state) dis_exp(:, round(t/h)+1);

    % Run the system
    [t_exp, x_exp] = discrete_attitude_equation(Jinertia, state0, Bf2tau, force_f, dis_f, h, tspan);
    x_exp = x_exp';
    Dstate0(:,:,itr) = x_exp(:,1:num_steps-1);
    Dstate1(:,:,itr) = x_exp(:,2:num_steps);
    Dinput0(:,:,itr) = force_exp;

    for ik = 1:num_steps-1
        bXI0(:,ik) = blkdiag( f_xiA1(x_exp(:,ik)), ...
                              f_xiA2(x_exp(:,ik)), ...
                              f_xiA3(x_exp(:,ik)), ...
                              f_xiA4(x_exp(:,ik)), ...
                              f_xiA5(x_exp(:,ik)), ...
                              f_xiA6(x_exp(:,ik)) ...
                             ) * x_exp(:,ik); 
        
        bUI0(:,ik) = blkdiag( f_xiB1(x_exp(:,ik)), ...
                              f_xiB2(x_exp(:,ik)), ...
                              f_xiB3(x_exp(:,ik)), ...
                              f_xiB4(x_exp(:,ik)) ...
                             ) * force_exp(:,ik); 
    end

    bXI1 = x_exp(:,2:num_steps);
    bDI0 = dis_exp;
    BXI1 = [BXI1, bXI1];
    BXI0 = [BXI0, bXI0];
    BUI0 = [BUI0, bUI0];
    BDI0 = [BDI0, bDI0];
end



% Plot first 3 curves in Figure 1
figure(1); hold on;            
for i = 1:3        
    plot(x_exp(i, :), 'LineWidth', 1.5);
end
hold off;           % Release figure hold
legend('Curve 1', 'Curve 2', 'Curve 3');
grid on;

% Plot last 3 curves in Figure 2
figure(2); hold on;            
for i = 4:6         
    plot(x_exp(i, :), 'LineWidth', 1.5);
end
hold off;           % Release figure hold
legend('Curve 4', 'Curve 5', 'Curve 6');
grid on;




DATATEST = [EA1, EA2, EA3, EA4, EA5, EA6]*BXI0 + [EB1, EB2, EB3, EB4]*BUI0 + BDI0 - BXI1;
figure('Color','w');
plot(DATATEST(4,:));


THETAnoise = roundUpSignificant(max(svd(BDI0*BDI0')), 2);
disp("THETAnoise eig is " + THETAnoise);


BXI1 = BXI1 + randn(size(BXI1))*0.00;
BXI0 = BXI0 + randn(size(BXI0))*0.00;
BUI0 = BUI0 + randn(size(BUI0))*0.00;


dataA = [BXI0; BUI0]*[BXI0; BUI0]';
dataB = -BXI1*[BXI0; BUI0]';
dataC = BXI1*BXI1' - THETAnoise*eye(dim_x)*1;

disp("min eig is " + min(eig(dataA)));






%% solve the controller ===================================================

% set the domain: |x| <= rx
rx = 0.4; 

% XIA
xiA11 = 1;

xiA12 = 1;

xiA13 = 1;

xiA14 = 1;
xiA24_u = rx; xiA24_l = -rx; 

xiA15 = 1;
xiA25_u = sin(rx)*tan(rx) ; xiA25_l = -sin(rx)*tan(rx);
xiA35_u = 1; xiA35_l = cos(rx);
xiA45_u = sin(rx)/cos(rx); xiA45_l = -sin(rx)/cos(rx);
xiA55_u = rx; xiA55_l = -rx;

xiA16 = 1;
xiA26_u = tan(rx) ; xiA26_l = -tan(rx);
xiA36_u = sin(rx) ; xiA36_l = -sin(rx);
xiA46_u = 1/cos(rx) ; xiA46_l = cos(rx);
xiA56_u = rx; xiA56_l = -rx;

% XIB
xiB11 = 1;
xiB12 = 1;
xiB13 = 1;
xiB14 = 1;

% the set of barQ
barQ = funcBarQ(xiA11, xiA12, xiA13, ...
                xiA14, xiA24_u, xiA24_l, ...
                xiA15, xiA25_u, xiA25_l, xiA35_u, xiA35_l, xiA45_u, xiA45_l, xiA55_u, xiA55_l, ...
                xiA16, xiA26_u, xiA26_l, xiA36_u, xiA36_l, xiA46_u, xiA46_l, xiA56_u, xiA56_l, ...
                xiB11, xiB12, xiB13, xiB14);


% solve sdp LMI
cvx_begin sdp % quiet
    variable epGa semidefinite;
    variable lyGa(dim_x,dim_x) semidefinite;
    variable kY(dim_u,dim_x);
    % variable mu_l semidefinite;
    % variable mu_u semidefinite;
    
    % minimize( mu_u - 0*mu_l + 1*epGa );
    minimize( 0.6*lambda_max(lyGa) - lambda_min(lyGa) - 0.1*epGa - 0*trace(lyGa) );

    subject to   
        for iv = 1:length(barQ)
            blockS = [ -lyGa-dataC,   zeros(dim_x),          dataB;
                       zeros(dim_x), -lyGa+epGa*eye(dim_x), -[lyGa;kY]'*barQ{iv}'; 
                       dataB',       -barQ{iv}*[lyGa;kY],   -dataA ];
            blockS <= 0;
        end
        epGa >= 0.00001;
        lyGa >= 0.0001 * eye(dim_x);
        % lyGa >= mu_l * eye(dim_x);
        % lyGa <= (mu_l+mu_u) * eye(dim_x);
        
cvx_end

vK = kY/lyGa;

% region of attraction
roac = sqrt( maxEig(lyGa)*minEig(lyGa) / ( maxEig(lyGa)^2 - epGa*minEig(lyGa) ) );
roa  = min( 1, roac ) * rx;
disp("radius of ROA is " + roa);






%% controller implementation ==============================================

% state0_imp = ones(dim_x,1)*0.2;
% state0_imp = randn(dim_x,1)*0.1;
state0_imp = [0.1 0.1 0.1 -0.1 -0.1 -0.1]';
tspan_imp = [0 25];

% Torque function that, state feedback
force_fk = @(t,state) vK*state;
[t_imp, x_imp] = discrete_attitude_equation(Jinertia, state0_imp, Bf2tau, force_fk, 0, h, tspan_imp);
x_imp = x_imp';


figure('color', [1 1 1]);
set(gcf, 'Position', [100, 100, 450, 350]);

subplot(2,1,1); % 2 rows, 1 column, 1st subplot
hold on;
for i = 1:3
    plot(t_imp', x_imp(i,:), 'LineWidth', 1.5);
end
hold off;
legend('$\phi$', '$\theta$', '$\psi$', 'Fontname', 'Times New Roman', 'Interpreter', 'latex', 'FontSize', 12);
xlabel('time [s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
ylabel('Euler angles [rad]', 'Fontname', 'Times New Roman', 'FontSize', 11);
set(gca,'fontsize',11,'fontname','Times');
grid on;
set(gca,'position',[0.13 0.63 0.84 0.32]);

% Bottom subplot - last 3 curves
subplot(2,1,2); % 2 rows, 1 column, 2nd subplot
hold on;
for i = 4:6
    plot(t_imp', x_imp(i,:), 'LineWidth', 1.5);
end
hold off;
legend('$\omega_1$', '$\omega_2$', '$\omega_3$', 'Fontname', 'Times New Roman', 'Interpreter', 'latex', 'FontSize', 12);
xlabel('time [s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
ylabel('angular velocity [rad/s]', 'Fontname', 'Times New Roman', 'FontSize', 11);
set(gca,'fontsize',11,'fontname','Times');
grid on;
set(gca,'position',[0.13 0.15 0.84 0.32]);






%% useful functions =======================================================


function [t_discrete, state_discrete] = discrete_attitude_equation(I, state0, Bf2tau, f_func, dis_fun, h, tspan)
    % Discrete-time Attitude Dynamics Solver (Forward Euler Method)
    % Solves coupled Euler-angle kinematics and Euler's rotation equations with:
    %   - Force-to-torque conversion via actuator configuration matrix
    %   - Additive state disturbance inputs
    %
    % Inputs:
    %   I: 3x3 inertia matrix [kg*m^2] (diagonal or full, must be positive definite)
    %   state0: Initial state [phi; theta; psi; omega_x; omega_y; omega_z] (6x1)
    %           Angles in radians, angular rates in rad/s
    %   Bf2tau: 3xn matrix converting actuator forces to body torques [m] (tau = Bf2tau * f)
    %           n = number of actuators (typically 3 or 4 for spacecraft/robots)
    %   f_func: Force input (function handle @(t,state) or constant nx1 vector) [N]
    %   dis_fun: Disturbance input (function handle @(t,state) or constant 6x1 vector)
    %            Additive to state derivatives [rad/s for angles, rad/s^2 for rates]
    %   h: Time step size [s] (scalar)
    %   tspan: Simulation time range [t_start, t_end] [s]
    %
    % Outputs:
    %   t_discrete: Time vector (Nx1) [s]
    %   state_discrete: State history matrix [phi,theta,psi,omega_x,omega_y,omega_z] (Nx6)
    %                  Angles in radians, angular rates in rad/s

    % Initialize time vector (column vector for consistency)
    t_discrete = (tspan(1):h:tspan(2))';
    N = length(t_discrete);
    state_discrete = zeros(N, 6);
    state_discrete(1,:) = state0(:)';  % Force row vector storage for output consistency

    % Main integration loop
    for k = 1:N-1
        t_k = t_discrete(k);
        state_k = state_discrete(k,:)';  % Current state (column vector)
        
        % --- Input Processing ---
        % 1. Force-to-torque conversion
        if isa(f_func, 'function_handle')
            % Dynamic force input (e.g., time-varying control)
            tau_k = Bf2tau * f_func(t_k, state_k);  
        else
            % Constant force input
            tau_k = Bf2tau * f_func;               
        end
        
        % 2. Disturbance processing
        if isa(dis_fun, 'function_handle')
            % Time/state-dependent disturbance (e.g., environmental noise)
            dis_k = dis_fun(t_k, state_k);  
        else
            % Constant disturbance (e.g., sensor bias)
            dis_k = dis_fun;               
        end
        
        % --- State Decomposition ---
        angles_k = state_k(1:3);  % Euler angles [phi (roll); theta (pitch); psi (yaw)] [rad]
        omega_k = state_k(4:6);   % Body-frame angular velocity [rad/s]
        
        % --- Kinematic Equations (ZYX Convention) ---
        phi = angles_k(1);    
        theta = angles_k(2);  
        
        % Singularity check (89.4° < |pitch| < 90.6°)
        if abs(cos(theta)) < 1e-2
            error('Gimbal lock: Pitch=±90°. Use quaternions or DCM for full attitude representation.');
        end
        
        % Euler angle rate calculation
        euler_dot = [...
            omega_k(1) + sin(phi)*tan(theta)*omega_k(2) + cos(phi)*tan(theta)*omega_k(3);  % phi_dot
            cos(phi)*omega_k(2) - sin(phi)*omega_k(3);                                    % theta_dot
            (sin(phi)/cos(theta))*omega_k(2) + (cos(phi)/cos(theta))*omega_k(3)           % psi_dot
        ];
        
        % --- Dynamic Equations ---
        % Euler's rotation equations with coriolis term
        omega_dot = I \ (tau_k - cross(omega_k, I*omega_k));  % [rad/s^2]
        
        % --- Forward Euler Integration ---
        % State update with disturbance injection
        state_discrete(k+1,:) = (state_k + h * [euler_dot; omega_dot] + dis_k)';
    end
end





function BarQ = funcBarQ(a1, a2, a3, ...
                         a14, a24_u, a24_l, ...
                         a15, a25_u, a25_l, a35_u, a35_l, a45_u, a45_l, a55_u, a55_l, ...
                         a16, a26_u, a26_l, a36_u, a36_l, a46_u, a46_l, a56_u, a56_l, ...
                         b1, b2, b3, b4)
    % Generate all 512 (2^9) combinations of upper/lower variants
    % Inputs: 
    %   a* : Component matrices
    %   *_u : Upper bound variants
    %   *_l : Lower bound variants
    % Output:
    %   BarQ : 512x1 cell array of blkdiag matrices
    
    % Define all possible combinations (binary combinations for 9 parameters)
    combinations = dec2bin(0:511) - '0'; % 512x9 binary matrix
    
    % Preallocate output
    BarQ = cell(512, 1);
    
    % Generate each combination
    for i = 1:512
        % Select variants based on binary flags
        idx = combinations(i,:);
        
        % Choose a24 variant
        a24 = idx(1)*a24_u + (1-idx(1))*a24_l;
        
        % Choose a25/a35/a45/a55 variants
        a25 = idx(2)*a25_u + (1-idx(2))*a25_l;
        a35 = idx(3)*a35_u + (1-idx(3))*a35_l;
        a45 = idx(4)*a45_u + (1-idx(4))*a45_l;
        a55 = idx(5)*a55_u + (1-idx(5))*a55_l;
        
        % Choose a26/a36/a46/a56 variants
        a26 = idx(6)*a26_u + (1-idx(6))*a26_l;
        a36 = idx(7)*a36_u + (1-idx(7))*a36_l;
        a46 = idx(8)*a46_u + (1-idx(8))*a46_l;
        a56 = idx(9)*a56_u + (1-idx(9))*a56_l;
        
        % Build the block diagonal matrix
        BarQ{i} = blkdiag(a1, a2, a3, ...
                          [a14; a24], ...
                          [a15; a25; a35; a45; a55], ...
                          [a16; a26; a36; a46; a56], ...
                          b1, b2, b3, b4);
    end
end


function e_max = maxEig( MatrixSym )
    e_max = max(eig(MatrixSym));
end

function e_min = minEig( MatrixSym )
    e_min = min(eig(MatrixSym));
end

function y = roundUpSignificant(x, n)
    magnitude = 10.^floor(log10(abs(x)) - n + 1);
    y = ceil(x ./ magnitude) .* magnitude;
    y(x == 0) = 0; 
end



