clear; close; clc;

% system dimension
dim_x = 3;
dim_u = 3;

%% system parameters values ===============================================
% the inertia matrix with respect to the body-fixed frame
J11 = 0.0820; J22 = 0.0845; J33 = 0.1377;
Jinertia = blkdiag(J11,J22,J33);
% the distance from the center of mass to the center of each rotor
d_c2c = 0.315;
% coefficient, torque generated by the i-th propeller about b3
c_f2tau = 8.004e-3;


% Time step for discrete method
h = 0.01;  




%% model based controllers ================================================
% set the domain: |x| <= rx
rx = 10; 

% A(x)
a11 = 1;
a21_u = h*(J33-J11)/J22*rx;
a21_l = h*(J33-J11)/J22*(-rx);
a31 = 0;

a12 = 0;
a22 = 1;
a32_u = h*(J11-J22)/J33*rx;
a32_l = h*(J11-J22)/J33*(-rx);

a13_u = h*(J22-J33)/J11*rx;
a13_l = h*(J22-J33)/J11*(-rx);
a23 = 0;
a33 = 1;

% B(x)
b11 = h/J11; b21 = 0; b31 = 0;
b12 = 0; b22 = h/J22; b32 = 0;
b13 = 0; b23 = 0; b33 = h/J33;

% the set of barG
barG = {
    [a11,   a12,   a13_u, b11, b12, b13;
     a21_u, a22,   a23,   b21, b22, b23;
     a31,   a32_u, a33,   b31, b32, b33];

    [a11,   a12,   a13_u, b11, b12, b13;
     a21_l, a22,   a23,   b21, b22, b23;
     a31,   a32_u, a33,   b31, b32, b33];

    [a11,   a12,   a13_u, b11, b12, b13;
     a21_u, a22,   a23,   b21, b22, b23;
     a31,   a32_l, a33,   b31, b32, b33];

    [a11,   a12,   a13_u, b11, b12, b13;
     a21_l, a22,   a23,   b21, b22, b23;
     a31,   a32_l, a33,   b31, b32, b33];

    [a11,   a12,   a13_l, b11, b12, b13;
     a21_u, a22,   a23,   b21, b22, b23;
     a31,   a32_u, a33,   b31, b32, b33];

    [a11,   a12,   a13_l, b11, b12, b13;
     a21_l, a22,   a23,   b21, b22, b23;
     a31,   a32_u, a33,   b31, b32, b33];

    [a11,   a12,   a13_l, b11, b12, b13;
     a21_u, a22,   a23,   b21, b22, b23;
     a31,   a32_l, a33,   b31, b32, b33];

    [a11,   a12,   a13_l, b11, b12, b13;
     a21_l, a22,   a23,   b21, b22, b23;
     a31,   a32_l, a33,   b31, b32, b33];
};




barU = 0.1; % actuator saturation

% solve sdp LMI
cvx_begin sdp % quiet
    variable epGa semidefinite;
    variable lyGa(dim_x,dim_x) semidefinite;
    variable kY(dim_u,dim_x);
    variable kW(dim_u,dim_x);
    variable kS(dim_u,dim_u) diagonal semidefinite;
    
    minimize( lambda_max(lyGa) - lambda_min(lyGa) - 0.1*epGa - 0.1*trace(lyGa) );


    subject to   
        for iu = 1:dim_u
            blockW = [ lyGa,     kW(iu,:)';
                       kW(iu,:), barU^2 ];
            blockW >= 0;
        end

        for iv = 1:length(barG)
            blockS = [ -lyGa+epGa*eye(dim_x), -(kY+kW)',                          [lyGa;kY]'*barG{iv}';
                       -(kY+kW),              -2*kS,                              [zeros(dim_x,dim_u);kS]'*barG{iv}';
                       barG{iv}*[lyGa;kY],     barG{iv}*[zeros(dim_x,dim_u);kS], -lyGa ];
            blockS <= 0;
        end
        epGa >= 0.001;
        lyGa >= 0.01 * eye(dim_x);
        
cvx_end

vK = kY/lyGa;
lyP = inv(lyGa);

disp(lyGa);

% region of attraction
roac = sqrt( maxEig(lyGa)*minEig(lyGa) / ( maxEig(lyGa)^2 - epGa*minEig(lyGa) ) );
roa  = min( 1, roac ) * rx;
disp("radius of ROA is " + roa);







%% controller implementation ==============================================
omega0 = [5.5; -2.7; 7.3];
tspan = [0, 20];
[t_dis, x_dis] = discrete_euler_equation(Jinertia, omega0, h, tspan, vK, barU);
% Plot 
figure('color', [1 1 1]);
component_names = {'\omega_1', '\omega_2', '\omega_3'};
for i = 1:3
    subplot(3,1,i);
    plot(t_dis, x_dis(:,i), 'b-', 'LineWidth', 1.5); hold on;
    ylabel(component_names{i});
    grid on;
end
xlabel('Time (s)');







%% plot the region of attraction ==========================================


% Generate unit sphere data
N = 50;  % Resolution
[xs, ys, zs] = sphere(N);

% ----------------------------
% Generate the sphere
% ----------------------------
X_sphere = roa * xs;
Y_sphere = roa * ys;
Z_sphere = roa * zs;

% ----------------------------
% Generate the ellipsoid x^T P x = 1
% ----------------------------
L = chol(lyP, 'lower');                   % Cholesky decomposition: P = L * L'
points = [xs(:)'; ys(:)'; zs(:)'];        % Flatten sphere grid
ellipsoid_pts = L \ points;               % Transform to ellipsoid
X_ellip = reshape(ellipsoid_pts(1,:), size(xs));
Y_ellip = reshape(ellipsoid_pts(2,:), size(ys));
Z_ellip = reshape(ellipsoid_pts(3,:), size(zs));

% ----------------------------
% Plot both surfaces
% ----------------------------
figure('Color', 'w');

% Plot the ellipsoid
surf(X_ellip, Y_ellip, Z_ellip, ...
    'FaceAlpha', 0.5, 'EdgeColor', 'none', 'FaceColor', [0 0.447 0.741]);
hold on;

% Plot the sphere
surf(X_sphere, Y_sphere, Z_sphere, ...
    'FaceAlpha', 0.2, 'EdgeColor', 'none', 'FaceColor', [0.85 0.325 0.098]);

% Axes settings
axis equal;
xlabel('x_1'); ylabel('x_2'); zlabel('x_3');
title('Sphere and Ellipsoid in 3D');
legend('Ellipsoid: $x^T P x = 1$', 'Sphere: $||x|| = r$', ...
    'Interpreter', 'latex', 'Location', 'best');
grid on;
view(3);





















%% useful fuction =========================================================
function e_max = maxEig( MatrixSym )
    e_max = max(eig(MatrixSym));
end

function e_min = minEig( MatrixSym )
    e_min = min(eig(MatrixSym));
end



function [t_discrete, omega_discrete] = discrete_euler_equation(I, omega0, h, tspan, Ctrl, baru)
    % Discrete-time Euler equations for rigid body rotation (Forward Euler method)
    %
    % Inputs:
    %   I        : Inertia tensor (3x3 matrix)
    %   omega0   : Initial angular velocity vector (3x1)
    %   h        : Time step size
    %   tspan    : Time interval as [t0, tf]
    %   Ctrl     : controller Ctrl, tau = Ctrl*omega
    %   baru     : saturation (positive scalar number)
    % Outputs:
    %   t_discrete      : Discrete time vector (N x 1)
    %   omega_discrete  : Angular velocity (N x 3)

    % Initialize time vector as column
    t_discrete = (tspan(1):h:tspan(2))';
    N = length(t_discrete);
    omega_discrete = zeros(N, 3);
    omega_discrete(1,:) = omega0(:)';

    % Time-stepping loop
    for k = 1:N-1
        omega_k = omega_discrete(k,:)';

        % Evaluate torque
        tau_k = Ctrl*omega_k;
        bar_u = baru*ones(size(tau_k));
        tau_k = min(max(tau_k, -bar_u), bar_u);

        % Compute angular acceleration
        omega_dot = I \ (tau_k - cross(omega_k, I * omega_k));

        % Forward Euler update
        omega_discrete(k+1,:) = (omega_k + h * omega_dot)';
    end
end



